{% set name = "lexicalrichness" %}
{% set version = "0.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 128734f0347c5c0a5a21f7b8e505ba79d5d54a45a7cf21b063902c5b0034c82d

build:
  number: 2
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}
    - scipy >=1.0.0
    - textblob >=0.15.3
    - matplotlib
    - pandas

test:
  requires:
    - python {{ python_min }}
  imports:
    - lexicalrichness

about:
  home: https://github.com/LSYS/lexicalrichness
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small module to compute textual lexical richness (aka lexical diversity).
  doc_url: https://github.com/LSYS/LexicalRichness/blob/master/README.rst
  dev_url: https://github.com/LSYS

extra:
  recipe-maintainers:
    - lsys
