{% set name = "lexicalrichness" %}
{% set version = "0.4.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 68fd0e42a102ea2df04d1173e9a3f27b15efc42ea74c3006f9d52c06b73a591a

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7
    - scipy >=1.0.0
    - textblob >=0.15.3
    - matplotlib
    - pandas

test:
  imports:
    - lexicalrichness

about:
  home: https://github.com/LSYS/lexicalrichness
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A small module to compute textual lexical richness (aka lexical diversity).
  doc_url: https://github.com/LSYS/LexicalRichness/blob/master/README.rst
  dev_url: https://github.com/LSYS

extra:
  recipe-maintainers:
    - lsys
